CFGS = { 'cvt-13-72x72': dict(INPUT_SIZE=(72, 72)
                                NUM_STAGES= 3,
                                PATCH_SIZE=[3, 2, 2],
                                PATCH_STRIDE=[2, 1, 1],
                                PATCH_PADDING= ['same','same' ,'same' ],
                                DIM_EMBED= [16, 64, 192],
                                NUM_HEADS= [1, 3, 6],
                                DEPTH= [1, 2, 10],
                                MLP_RATIO= [2.0, 2.0, 2.0],
                                ATTN_DROP_RATE= [0.0, 0.0, 0.0],
                                DROP_RATE= [0.0, 0.0, 0.0],
                                DROP_PATH_RATE= [0.0, 0.0, 0.1],
                                QKV_BIAS= [True, True, True],
                                CLS_TOKEN= [False, False, True],
                                POS_EMBED= [False, False, False],
                                QKV_PROJ_METHOD= ['dw_bn', 'dw_bn', 'dw_bn'],
                                KERNEL_QKV= [2, 2, 2],
                                PADDING_KV= ['same','same' ,'same' ],
                                STRIDE_KV= [2, 2, 2],
                                PADDING_Q= ['same','same' ,'same' ],
                                STRIDE_Q= [1, 1, 1])
         }
